### ISSUE TITLE
Missing icons and dlls

### ISSUE THREAD

**Issue by r3sus** [DUB1401/Dweller-Legacy-Edition#1]
Hey, thanks for the project, I had issues running the project: first it was missing icons which I commented out in rc. The resulting build wouldn't run without SFML DLLs. The latest SFML release misses some function. Static linking instead of dynamic might probably solve this issue. Also it would be good to have binary release. Please, have a look.

**Comment by DUB1401** [comment]
Thank you for your feedback, but I'm not going to add icons and an executable file yet. Apart from the introductory video, little is ready, so I don't think it's necessary at the moment.

**Comment by r3sus** [comment]
Thanks. Anyway, I did find J2SE version which don't needs an emulator and works well.
